name: CI/CD Pipeline da API Flask

on: [push, pull_request]

jobs:
  build_and_test:
    name: Build, Teste e Qualidade
    runs-on: ubuntu-latest
    
    # REMOVIDO: O 'defaults: working-directory' foi removido,
    # pois a pasta de configuração .github não está mais em lab_api.
    
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      #  NOVO: Usamos 'cd lab_api' para mudar o diretório de trabalho antes de rodar o Docker Compose.
      - name: Executar Testes Unitários com Docker Compose
        run: |
          echo "Iniciando a construção da imagem e execução dos testes..."
          cd lab_api 
          docker-compose run --rm api python test_app.py 
          echo "Testes concluídos."

      - name: Limpeza de containers e rede
        if: always()
        run: |
          cd lab_api
          docker-compose down